# Generated by Django 6.0.2 on 2026-02-16 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=20)),
                ('dueno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='web.dueno')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('laboratorio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExpedienteMedico',
            fields=[
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='expediente', serialize=False, to='web.mascota')),
                ('fecha_ultima_visita', models.DateField()),
                ('diagnostico', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacunas',
            field=models.ManyToManyField(related_name='mascotas_vacunas', to='web.vacuna'),
        ),
    ]
